version: "3.9"
   
services:
  db:
    image: mysql:8.0
    container_name: db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  php:
    build: ./php
    container_name: php
    command: php artisan serve --host=0.0.0.0 --port=80
    restart: unless-stopped
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      - db
  python:
    build: ./python
    container_name: python
    command: python manage.py runserver 0.0.0.0:80
    restart: unless-stopped
    ports:
      - "5000:80"
    env_file:
      - .env
    depends_on:
      - db
