# Generated by Django 4.0.3 on 2022-03-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
